// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPLIyPSWb6zb1Wzk9Ah8aNZhQCIigFZs',
    appId: '1:943857388704:web:5a72a7b249eb63574d4dc5',
    messagingSenderId: '943857388704',
    projectId: 'travelwise-b5ee3',
    authDomain: 'travelwise-b5ee3.firebaseapp.com',
    databaseURL: 'https://travelwise-b5ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travelwise-b5ee3.appspot.com',
    measurementId: 'G-EC3VQVF8S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hCJVI9pC4NN4Qqvom1flIADbGf3mbxE',
    appId: '1:943857388704:android:eba1f57d070edc0e4d4dc5',
    messagingSenderId: '943857388704',
    projectId: 'travelwise-b5ee3',
    databaseURL: 'https://travelwise-b5ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travelwise-b5ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI93MEH3-FmBETm-4KkM60qYFCa5ziM5A',
    appId: '1:943857388704:ios:745e1e35f2079f6b4d4dc5',
    messagingSenderId: '943857388704',
    projectId: 'travelwise-b5ee3',
    databaseURL: 'https://travelwise-b5ee3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travelwise-b5ee3.appspot.com',
    iosClientId: '943857388704-7mrc65j98q09cumnvj5odc243lbdukdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelwise',
  );
}
